import streamlit as st
from display import Presentation

# Set page title and layout
st.set_page_config(
    page_title="CPI Machine",
    layout="wide",
)

present = Presentation()

st.title("Consumer Price Index in the USA")
present.cpi()
# Define the HTML content with CSS for justification, font size, and spacing between paragraphs
html_content = """
<div style="text-align: justify; font-size: 12px;">
    <p>The Consumer Price Index for All Urban Consumers: All Items (CPIAUCSL) is a price index of a basket of goods and services paid by urban consumers in the United States. It is compiled by the U.S. Bureau of Labor Statistics and measures changes in the price level of this basket over time. The index is used to assess price changes associated with the cost of living and is a key indicator of inflation. The data reflects the spending patterns of urban consumers, which represent approximately 93% of the total U.S. population. The CPI is widely used by policymakers, economists, and the general public to understand inflation trends and make informed economic decisions.</p>
    
    <p style="margin-top: 20px;">The Consumer Price Index for All Urban Consumers: All Items Less Food and Energy (CPILFESL) is a price index that measures the changes in the cost of a basket of goods and services, excluding the volatile food and energy sectors. This index is also compiled by the U.S. Bureau of Labor Statistics and is used to provide a clearer view of the underlying inflation trends by excluding the often fluctuating prices of food and energy. The CPILFESL is a crucial indicator for policymakers and economists as it helps in understanding the long-term inflationary pressures in the economy without the short-term noise caused by food and energy price changes. Like the broader CPI, this index reflects the spending patterns of urban consumers, representing a significant portion of the U.S. population.</p>
    
    <p style="margin-top: 20px;">The model used for predictions is trained on historical data from 1960 up to 2023. Therefore, the predictions generated by the model start from the year 2024 onwards. It is important to note that the model may make mistakes, and individual predictions might not always be accurate. However, the reliability of the model's predictions can be assessed based on their average accuracy over time. Users should consider this when interpreting the results, as the model's strength lies in its ability to provide insights based on long-term trends rather than precise short-term forecasts.</p>
</div>
"""

# Render the HTML content in Streamlit
st.markdown(html_content, unsafe_allow_html=True)
